/* ================================================
   data.js — Catálogo de productos

   PARA AGREGAR FOTO A UN PRODUCTO:
   1. Copia la foto dentro de la carpeta  img/
   2. Quita el  //  del campo img del producto
   3. Escribe el nombre exacto del archivo

   Ejemplo:
     // img: 'img/carta-500.jpg',   <- con //  = desactivado
        img: 'img/carta-500.jpg',   <- sin //  = activado

   Si la foto no existe, se muestra el emoji solo.
   ================================================ */

const PRODUCTS = [

  // OFICINA — Hojas de papel
  { id: 1,  name: 'Carta 500 Hojas',               cat: 'Oficina',    icon: '📄',
    // img: 'img/carta-500.jpg',
    desc: 'Papel A4 Blanco, paquete x500 hojas' },
  { id: 2,  name: 'Carta 300 Hojas Cuadriculadas',  cat: 'Oficina',    icon: '📄',
    // img: 'img/carta-300.jpg',
    desc: 'Hojas de papel cuadriculado' },
  { id: 3,  name: 'Oficio 500 Hojas',               cat: 'Oficina',    icon: '📄',
    // img: 'img/oficio-500.jpg',
    desc: 'Papel para impresoras tamaño oficio' },

  // OFICINA — Cuadernos
  { id: 4,  name: 'Cuaderno Rayado',                cat: 'Oficina',    icon: '📓',
    // img: 'img/cuaderno-rayado.jpg',
    desc: 'Argollados, papel cartulina de colores' },
  { id: 5,  name: 'Cuaderno Cuadriculado',          cat: 'Oficina',    icon: '📓',
    // img: 'img/cuaderno-cuadriculado.jpg',
    desc: 'Azul, verde y rojo' },
  { id: 6,  name: 'Libreta Punteada',               cat: 'Oficina',    icon: '📓',
    // img: 'img/libreta-punteada.jpg',
    desc: 'Blanco y amarillo, bullet journal' },

  // OFICINA — Escritorio
  { id: 7,  name: 'Grapadora & Grapas',             cat: 'Oficina',    icon: '📌',
    // img: 'img/grapadora.jpg',
    desc: 'Grandes, medianas, pequeñas' },
  { id: 8,  name: 'Perforadora',                    cat: 'Oficina',    icon: '⚙️',
    // img: 'img/perforadora.jpg',
    desc: 'Carpeta de 2 y 3 puestos' },
  { id: 9,  name: 'Clips & Sujetapapeles',          cat: 'Oficina',    icon: '📎',
    // img: 'img/clips.jpg',
    desc: 'Metálico o plástico' },
  { id: 10, name: 'Tijeras',                        cat: 'Oficina',    icon: '✂️',
    // img: 'img/tijeras.jpg',
    desc: 'Grandes, medianas y pequeñas' },
  { id: 11, name: 'Pegante',                        cat: 'Oficina',    icon: '🧴',
    // img: 'img/pegante.jpg',
    desc: 'En barra o líquido (Colbón)' },
  { id: 12, name: 'Reglas',                         cat: 'Oficina',    icon: '📏',
    // img: 'img/reglas.jpg',
    desc: 'Plásticas o metálicas' },
  { id: 13, name: 'Compás',                         cat: 'Oficina',    icon: '🔵',
    // img: 'img/compas.jpg',
    desc: 'Punta fija, 3 puntas, de marcador' },
  { id: 14, name: 'Escuadra',                       cat: 'Oficina',    icon: '📐',
    // img: 'img/escuadra.jpg',
    desc: 'Aluminio, acero inoxidable, 90°' },
  { id: 15, name: 'Borrador',                       cat: 'Oficina',    icon: '🩹',
    // img: 'img/borrador.jpg',
    desc: 'Para tablero, para cuaderno' },
  { id: 16, name: 'Lápiz',                          cat: 'Oficina',    icon: '✏️',
    // img: 'img/lapiz.jpg',
    desc: 'Caja por 12 unidades' },
  { id: 17, name: 'Bolígrafo',                      cat: 'Oficina',    icon: '🖊️',
    // img: 'img/boligrafo.jpg',
    desc: 'Color rojo & negro' },
  { id: 18, name: 'Bandas de Caucho',               cat: 'Oficina',    icon: '🔶',
    // img: 'img/bandas-caucho.jpg',
    desc: 'Cajas por 100 unidades' },
  { id: 19, name: 'Bisturí',                        cat: 'Oficina',    icon: '🔪',
    // img: 'img/bisturi.jpg',
    desc: 'Cuchilla retráctil, base de corte' },
  { id: 20, name: 'Cortador Exacto',                cat: 'Oficina',    icon: '🔪',
    // img: 'img/cortador-exacto.jpg',
    desc: 'Con cuchilla retráctil' },

  // PAPELERÍA
  { id: 21, name: 'Marcadores de Pizarra',          cat: 'Papelería',  icon: '🖍️',
    // img: 'img/marcadores-pizarra.jpg',
    desc: 'Caja de 8 colores' },
  { id: 22, name: 'Resaltadores',                   cat: 'Papelería',  icon: '✒️',
    // img: 'img/resaltadores.jpg',
    desc: 'Precio individual' },
  { id: 23, name: 'Corrector',                      cat: 'Papelería',  icon: '🖌️',
    // img: 'img/corrector.jpg',
    desc: 'Líquido o cinta' },
  { id: 24, name: 'Sobres de Manila',               cat: 'Papelería',  icon: '✉️',
    // img: 'img/sobres-manila.jpg',
    desc: 'Carta, oficio — precio individual' },
  { id: 25, name: 'Carpeta con Anilla 1.0',         cat: 'Papelería',  icon: '📁',
    // img: 'img/carpeta-1.jpg',
    desc: 'Pasta catálogo, blanca' },
  { id: 26, name: 'Carpeta con Anilla 2.5',         cat: 'Papelería',  icon: '📁',
    // img: 'img/carpeta-25.jpg',
    desc: 'Pasta catálogo grande' },
  { id: 27, name: 'Separadores de Carpeta',         cat: 'Papelería',  icon: '📂',
    // img: 'img/separadores.jpg',
    desc: 'Con encuadernados' },
  { id: 28, name: 'Papel Plotter',                  cat: 'Papelería',  icon: '🗃️',
    // img: 'img/papel-plotter.jpg',
    desc: 'Rollo, calidad superior gran formato' },
  { id: 29, name: 'Resma Carta',                    cat: 'Papelería',  icon: '📦',
    // img: 'img/resma-carta.jpg',
    desc: 'Propalcote x500 hojas' },
  { id: 30, name: 'Resma Oficio',                   cat: 'Papelería',  icon: '📦',
    // img: 'img/resma-oficio.jpg',
    desc: 'Tamaño oficio x500 hojas' },
  { id: 31, name: 'Témperas',                       cat: 'Papelería',  icon: '🎨',
    // img: 'img/temperas.jpg',
    desc: 'Gama de colores vibrantes' },
  { id: 32, name: 'Protector de Hojas',             cat: 'Papelería',  icon: '🗂️',
    // img: 'img/protector-hojas.jpg',
    desc: 'Transparencia, plástico alta calidad' },
  { id: 33, name: 'Almohadilla Dactilar',           cat: 'Papelería',  icon: '🖤',
    // img: 'img/almohadilla.jpg',
    desc: 'Impresiones precisas' },
  { id: 34, name: 'Portalápices',                   cat: 'Papelería',  icon: '✏️',
    // img: 'img/portalapices.jpg',
    desc: 'Malla negra' },
  { id: 35, name: 'Revistero',                      cat: 'Papelería',  icon: '📚',
    // img: 'img/revistero.jpg',
    desc: 'Malla negra' },
  { id: 36, name: 'Post-it Notes',                  cat: 'Papelería',  icon: '🟨',
    // img: 'img/post-it.jpg',
    desc: 'Banderas y memos' },

  // TECNOLOGÍA
  { id: 37, name: 'Disco Duro Externo',             cat: 'Tecnología', icon: '💾',
    // img: 'img/disco-duro.jpg',
    desc: 'Alta capacidad, portabilidad (Toshiba)' },
  { id: 38, name: 'Ratón Inalámbrico',              cat: 'Tecnología', icon: '🖱️',
    // img: 'img/raton.jpg',
    desc: 'Rendimiento preciso, sin interrupciones' },
  { id: 39, name: 'Teclado',                        cat: 'Tecnología', icon: '⌨️',
    // img: 'img/teclado.jpg',
    desc: 'Compacto, resistente a salpicaduras' },
  { id: 40, name: 'Pad Mouse',                      cat: 'Tecnología', icon: '🖱️',
    // img: 'img/pad-mouse.jpg',
    desc: 'Base antideslizante, superficie suave' },
  { id: 41, name: 'Calculadora',                    cat: 'Tecnología', icon: '🧮',
    // img: 'img/calculadora.jpg',
    desc: 'Casio, funciones avanzadas' },
  { id: 42, name: 'Cargadores y Cables USB',        cat: 'Tecnología', icon: '🔌',
    // img: 'img/cargadores-usb.jpg',
    desc: 'Carga rápida, varios tipos' },
  { id: 43, name: 'Audífono Alámbrico',             cat: 'Tecnología', icon: '🎧',
    // img: 'img/audifono.jpg',
    desc: 'Calidad de sonido excepcional' },
  { id: 44, name: 'Memorias USB',                   cat: 'Tecnología', icon: '💿',
    // img: 'img/memorias-usb.jpg',
    desc: 'Kingston 8GB, 16GB, 32GB, 64GB' },
  { id: 45, name: 'Base PC Portátil',               cat: 'Tecnología', icon: '💻',
    // img: 'img/base-pc.jpg',
    desc: 'Ventilación ergonómica, ajustable' },

  // EQUIPOS
  { id: 46, name: 'Valla Guillotina',               cat: 'Equipos',    icon: '✂️',
    // img: 'img/guillotina.jpg',
    desc: 'Cortes precisos en grandes volúmenes' },
  { id: 47, name: 'Laminadora',                     cat: 'Equipos',    icon: '🖨️',
    // img: 'img/laminadora.jpg',
    desc: 'Para cédulas, carnets, documentos' },
  { id: 48, name: 'Destructora de Papel',           cat: 'Equipos',    icon: '♻️',
    // img: 'img/destructora.jpg',
    desc: 'Seguridad de datos sensibles' },

  // OTROS
  { id: 49, name: 'Papeles de Colores',             cat: 'Otros',      icon: '🎨',
    // img: 'img/papeles-colores.jpg',
    desc: 'Colores suaves y sutiles' },
  { id: 50, name: 'Pizarra Blanca',                 cat: 'Otros',      icon: '⬜',
    // img: 'img/pizarra.jpg',
    desc: 'Con rotuladores incluidos' },
  { id: 51, name: 'Gomas de Borrar',                cat: 'Otros',      icon: '🩹',
    // img: 'img/gomas.jpg',
    desc: 'En barra, varias formas' },
  { id: 52, name: 'Sacapuntas',                     cat: 'Otros',      icon: '✏️',
    // img: 'img/sacapuntas.jpg',
    desc: 'Manual y automático' },
  { id: 53, name: 'Cinta Métrica',                  cat: 'Otros',      icon: '📏',
    // img: 'img/cinta-metrica.jpg',
    desc: 'Alta precisión' },
  { id: 54, name: 'Chinches',                       cat: 'Otros',      icon: '📌',
    // img: 'img/chinches.jpg',
    desc: 'Alta calidad, para tableros' },
  { id: 55, name: 'Cinta de Enmascarar',            cat: 'Otros',      icon: '🟨',
    // img: 'img/cinta-enmascarar.jpg',
    desc: 'Para pintura y manualidades' },
  { id: 56, name: 'Tableros Acrílicos',             cat: 'Otros',      icon: '⬜',
    // img: 'img/tableros.jpg',
    desc: 'Todos los tamaños' },
  { id: 57, name: 'Cintas Transparentes',           cat: 'Otros',      icon: '📦',
    // img: 'img/cintas-transparentes.jpg',
    desc: 'Todos los tamaños, embalaje' },
  { id: 58, name: 'Papelera de Malla',              cat: 'Otros',      icon: '🗑️',
    // img: 'img/papelera.jpg',
    desc: 'Malla negra' },
  { id: 59, name: 'Clips Mariposa',                 cat: 'Otros',      icon: '📎',
    // img: 'img/clips-mariposa.jpg',
    desc: 'Para sujetar documentos' },
  { id: 60, name: 'Carpeta A-Z Carta',              cat: 'Otros',      icon: '📁',
    // img: 'img/carpeta-az-carta.jpg',
    desc: 'Archivadores eficientes' },
  { id: 61, name: 'Carpeta A-Z Oficio',             cat: 'Otros',      icon: '📁',
    // img: 'img/carpeta-az-oficio.jpg',
    desc: 'Archivadores tamaño oficio' },
  { id: 62, name: 'Libros Contabilidad',            cat: 'Otros',      icon: '📒',
    // img: 'img/libros-contabilidad.jpg',
    desc: 'General, ingresos y egresos' },
  { id: 63, name: 'Folder Celuguía',                cat: 'Otros',      icon: '📂',
    // img: 'img/folder.jpg',
    desc: 'Vertical carta, elegante' },
  { id: 64, name: 'Sacagrapas',                     cat: 'Otros',      icon: '⚙️',
    // img: 'img/sacagrapas.jpg',
    desc: 'Ergonómico, sin dañar el papel' },
  { id: 65, name: 'Humedecedor Dactilar',           cat: 'Otros',      icon: '💧',
    // img: 'img/humedecedor.jpg',
    desc: 'Tecnología avanzada' },
  { id: 66, name: 'Gancho Legajador',               cat: 'Otros',      icon: '🔗',
    // img: 'img/gancho.jpg',
    desc: 'Acero inoxidable, metal recubierto' },
  { id: 67, name: 'Reposapies',                     cat: 'Otros',      icon: '🦶',
    // img: 'img/reposapies.jpg',
    desc: 'Ergonómico, ajustable' },
  { id: 68, name: 'Corrector en Cinta/Barra',       cat: 'Otros',      icon: '🖌️',
    // img: 'img/corrector-cinta.jpg',
    desc: 'Líquido y en barra' },
];

// Credenciales admin
const ADMIN_CREDENTIALS = { user: 'dlc_backup_2026', pass: 'DLC$B4rr4nquill4.2026!' };' };

// Email del administrador
const ADMIN_EMAIL = 'distribucionesestrategicasco@gmail.com';
